/**
 * 官方物品 id 常量（纯叶子模块）
 * 引擎里需要点名引用具体官方物品的位置（初始装备/初始饭团/碎矿映射等）
 * 统一从这里取，禁止再写裸字符串。
 * MOD 自己的内容 id 由 MOD 文件自行导出，不走这里。
 *
 * 注意：本文件必须保持"零 def 依赖"——矿物 Def 会反向引用物品 id，
 * 若这里 re-export 物品 def 文件会与矿物侧形成 import 环（运行时 TDZ）。
 */
import { vanilla } from '../../core/ids'

export const ORE_COPPER_ID = vanilla('ore_copper')
export const ORE_IRON_ID = vanilla('ore_iron')
export const ORE_GOLD_ID = vanilla('ore_gold')
export const RUBY_ID = vanilla('ruby')
export const ROCK_STONE_ID = vanilla('rock_stone')
export const PICK_RUSTY_ID = vanilla('pick_rusty')
export const SWORD_IRON_ID = vanilla('sword_iron')
export const SWORD_RUSTY_ID = vanilla('sword_rusty')
export const SPEAR_STONE_ID = vanilla('spear_stone')
export const SPEAR_TETANUS_ID = vanilla('spear_tetanus')
export const WOOD_SHIELD_ID = vanilla('wood_shield')
export const SPEAR_IRON_ID = vanilla('spear_iron')
export const SPEAR_RED_TASSEL_ID = vanilla('spear_red_tassel')
export const STAFF_WOOD_ID = vanilla('staff_wood')
export const KATANA_FORGED_ID = vanilla('katana_forged')
export const DAGGER_ASSAULT_ID = vanilla('dagger_assault')
export const SWORD_STEEL_BROAD_ID = vanilla('sword_steel_broad')
export const AXE_STEEL_ID = vanilla('axe_steel')
export const DUAL_BLADES_ID = vanilla('dual_blades')
export const BOOMERANG_ID = vanilla('boomerang')
export const WOOD_BOW_ID = vanilla('wood_bow')
export const ELASTIC_CORD_ID = vanilla('elastic_cord')
export const WOOD_ARROW_ID = vanilla('wood_arrow')
export const IRON_ARROW_ID = vanilla('iron_arrow')
export const TSUKINAGA_AI_TAROT_ID = vanilla('tsukinaga_ai_tarot')
export const NUNCHAKU_ID = vanilla('nunchaku')
export const PICK_IRON_ID = vanilla('pick_iron')
export const PICK_STEEL_ID = vanilla('pick_steel')
export const LEATHER_ARMOR_ID = vanilla('leather_armor')
export const DOOMSDAY_ID = vanilla('doomsday')
export const VORPAL_ID = vanilla('vorpal')
export const WHIP_ID = vanilla('whip')
export const WOOD_ID = vanilla('wood')
export const MUSHROOM_ID = vanilla('suspicious_mushroom')
export const HERB_ID = vanilla('herb')
export const SLIME_BALL_ID = vanilla('slime_ball')
export const SOUP_ID = vanilla('mushroom_soup')
export const SALT_SOUP_ID = vanilla('rock_salt_mushroom_soup')
export const HEMP_THREAD_ID = vanilla('coarse_hemp_thread')
export const COPPER_INGOT_ID = vanilla('copper_ingot')
export const IRON_INGOT_ID = vanilla('iron_ingot')
export const OLD_FURNACE_PARTS_ID = vanilla('old_furnace_parts')
export const CLOVER_ID = vanilla('four_leaf_clover')
export const DROOP_FRUIT_ID = vanilla('droop_fruit')
export const POISON_GRASS_ID = vanilla('poison_grass')
export const HEAT_NOZZLE_ID = vanilla('heat_resistant_nozzle')
export const COAL_ID = vanilla('coal')
export const ROCK_SALT_ID = vanilla('rock_salt')
export const FLAX_ID = vanilla('flax')
export const BAT_WING_ID = vanilla('bat_wing')
export const CRYSTAL_CORE_ID = vanilla('crystal_core')
export const SMALL_CRYSTAL_CORE_ID = vanilla('small_crystal_core')
export const STRANGE_GEL_ID = vanilla('strange_gel')
export const MISO_ID = vanilla('miso')
export const KEDAMA_TOFU_ID = vanilla('kedama_tofu')
export const FORGET_ME_NOT_ID = vanilla('forget_me_not')
export const SPELL_HARAE_ID = vanilla('spell_harae')
export const FOOD_ONIGIRI_ID = vanilla('food_onigiri')
/** 剧情道具：火柴（序章随锈镐一起捡到；只入背包，当前版本无使用机制） */
export const MATCHES_ID = vanilla('matches')
