import type { DialogueTree, DialogueNode } from '../../../../game/dialogue/types'
import { kedamaGirlPortraits } from '../../../characters/vanilla/fourthFloor'
import { bindStoryCG, storyCGs } from '../../cg'

/** 定稿原文逐节点保存；分段完成才推进持久状态。 */
export const FOURTH_TREES: Record<string, DialogueTree> = {
  intro: { id: 'touhou:fourth_intro', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.intro.s1', narration: true, os: true, next: 's2' },
    s2: { id: 's2', text: 'story.fourth.intro.s2', narration: true, os: true, next: 's3' },
    s3: { id: 's3', text: 'story.fourth.intro.s3', speaker: 'story.speaker.hero', next: 's4' },
    s4: { id: 's4', text: 'story.fourth.intro.s4', narration: true, os: true, next: 's5' },
    s5: { id: 's5', text: 'story.fourth.intro.s5', narration: true, os: true, next: 's6', effects: [{ type: 'action', name: 'fourth.appear' }] },
    s6: { id: 's6', text: 'story.fourth.intro.s6', narration: true, os: true, next: 's7' },
    s7: { id: 's7', text: 'story.fourth.intro.s7', narration: true, os: true, next: 's8' },
    s8: { id: 's8', text: 'story.fourth.intro.s8', speaker: 'story.speaker.hero', next: 's9' },
    s9: { id: 's9', text: 'story.fourth.intro.s9', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's10' },
    s10: { id: 's10', text: 'story.fourth.intro.s10', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's11' },
    s11: { id: 's11', text: 'story.fourth.intro.s11', speaker: 'story.speaker.hero', next: 's12' },
    s12: { id: 's12', text: 'story.fourth.intro.s12', speaker: 'story.speaker.hero', next: 's13' },
    s13: { id: 's13', text: 'story.fourth.intro.s13', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's14' },
    s14: { id: 's14', text: 'story.fourth.intro.s14', narration: true, os: true },
  } },
  phase: { id: 'touhou:fourth_phase', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.phase.s1', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's2' },
    s2: { id: 's2', text: 'story.fourth.phase.s2', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's3' },
    s3: { id: 's3', text: 'story.fourth.phase.s3', speaker: 'story.speaker.hero', next: 's4' },
    s4: { id: 's4', text: 'story.fourth.phase.s4', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss },
  } },
  defeat: { id: 'touhou:fourth_defeat', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.defeat.s1', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's2' },
    s2: { id: 's2', text: 'story.fourth.defeat.s2', narration: true, os: true, next: 's3', effects: [{ type: 'action', name: 'fourth.dropOrnaments' }] },
    s3: { id: 's3', text: 'story.fourth.defeat.s3', speaker: 'story.speaker.kedamaGirl', portrait: kedamaGirlPortraits.boss, next: 's4' },
    s4: { id: 's4', text: 'story.fourth.defeat.s4', narration: true, os: true, effects: [{ type: 'action', name: 'fourth.restore' }] },
  } },
  check: { id: 'touhou:fourth_check', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.check.s1', speaker: 'story.speaker.hero', next: 's2' },
    s2: { id: 's2', text: 'story.fourth.check.s2', narration: true, os: true, next: 's3' },
    s3: { id: 's3', text: 'story.fourth.check.s3', speaker: 'story.speaker.hero' },
  } },
  rescue: { id: 'touhou:fourth_rescue', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.rescue.s1', narration: true, os: true, next: 's2', effects: [{ type: 'action', name: 'fourth.free' }] },
    s2: { id: 's2', text: 'story.fourth.rescue.s2', speaker: 'story.speaker.hero', next: 's3' },
    s3: { id: 's3', text: 'story.fourth.rescue.s3', narration: true, os: true, next: 's4', effects: [{ type: 'action', name: 'fourth.bite' }] },
    s4: { id: 's4', text: 'story.fourth.rescue.s4', speaker: 'story.speaker.hero', next: 's5' },
    s5: { id: 's5', text: 'story.fourth.rescue.s5', speaker: 'story.speaker.girl', next: 's6' },
    s6: { id: 's6', text: 'story.fourth.rescue.s6', speaker: 'story.speaker.hero', next: 's7' },
    s7: { id: 's7', text: 'story.fourth.rescue.s7', speaker: 'story.speaker.girl', next: 's8' },
    s8: { id: 's8', text: 'story.fourth.rescue.s8', speaker: 'story.speaker.hero', next: 's9' },
    s9: { id: 's9', text: 'story.fourth.rescue.s9', narration: true, os: true, next: 's10', effects: [{ type: 'action', name: 'fourth.stopBite' }] },
    s10: { id: 's10', text: 'story.fourth.rescue.s10', speaker: 'story.speaker.girl', next: 's11' },
    s11: { id: 's11', text: 'story.fourth.rescue.s11', speaker: 'story.speaker.hero', next: 's12' },
    s12: { id: 's12', text: 'story.fourth.rescue.s12', speaker: 'story.speaker.girl', next: 's13' },
    s13: { id: 's13', text: 'story.fourth.rescue.s13', speaker: 'story.speaker.hero', next: 's14' },
    s14: { id: 's14', text: 'story.fourth.rescue.s14', narration: true, os: true, next: 's15' },
    s15: { id: 's15', text: 'story.fourth.rescue.s15', speaker: 'story.speaker.hero', next: 's16' },
    s16: { id: 's16', text: 'story.fourth.rescue.s16', speaker: 'story.speaker.girl', next: 's17' },
    s17: { id: 's17', text: 'story.fourth.rescue.s17', speaker: 'story.speaker.hero', next: 's18' },
    s18: { id: 's18', text: 'story.fourth.rescue.s18', narration: true, os: true, next: 's19' },
    s19: { id: 's19', text: 'story.fourth.rescue.s19', speaker: 'story.speaker.girl', next: 's20' },
    s20: { id: 's20', text: 'story.fourth.rescue.s20', speaker: 'story.speaker.hero', next: 's21' },
    s21: { id: 's21', text: 'story.fourth.rescue.s21', speaker: 'story.speaker.girl', next: 's22' },
    s22: { id: 's22', text: 'story.fourth.rescue.s22', speaker: 'story.speaker.hero', next: 's23' },
    s23: { id: 's23', text: 'story.fourth.rescue.s23', speaker: 'story.speaker.girl', next: 's24' },
    s24: { id: 's24', text: 'story.fourth.rescue.s24', speaker: 'story.speaker.hero', next: 's25' },
    s25: { id: 's25', text: 'story.fourth.rescue.s25', speaker: 'story.speaker.girl', next: 's26' },
    s26: { id: 's26', text: 'story.fourth.rescue.s26', speaker: 'story.speaker.hero', next: 's27' },
    s27: { id: 's27', text: 'story.fourth.rescue.s27', narration: true, os: true, effects: [{ type: 'action', name: 'fourth.carry' }] },
  } },
  arrival: { id: 'touhou:fourth_arrival', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.arrival.s1', narration: true, os: true, next: 's2' },
    s2: { id: 's2', text: 'story.fourth.arrival.s2', speaker: 'story.speaker.hero', next: 's3' },
    s3: { id: 's3', text: 'story.fourth.arrival.s3', narration: true, os: true, next: 's4' },
    s4: { id: 's4', text: 'story.fourth.arrival.s4', speaker: 'story.speaker.reimu', next: 's5', effects: [{ type: 'action', name: 'fourth.recognize' }] },
    s5: { id: 's5', text: 'story.fourth.arrival.s5', speaker: 'story.speaker.hero', next: 's6' },
    s6: { id: 's6', text: 'story.fourth.arrival.s6', narration: true, os: true, next: 's7' },
    s7: { id: 's7', text: 'story.fourth.arrival.s7', speaker: 'story.speaker.rumia', next: 's8' },
    s8: { id: 's8', text: 'story.fourth.arrival.s8', speaker: 'story.speaker.rumia', next: 's9' },
    s9: { id: 's9', text: 'story.fourth.arrival.s9', speaker: 'story.speaker.reimu', next: 's10' },
    s10: { id: 's10', text: 'story.fourth.arrival.s10', speaker: 'story.speaker.rumia', next: 's11' },
    s11: { id: 's11', text: 'story.fourth.arrival.s11', speaker: 'story.speaker.reimu', next: 's12' },
    s12: { id: 's12', text: 'story.fourth.arrival.s12', speaker: 'story.speaker.rumia', next: 's13' },
    s13: { id: 's13', text: 'story.fourth.arrival.s13', speaker: 'story.speaker.reimu', next: 's14' },
    s14: { id: 's14', text: 'story.fourth.arrival.s14', speaker: 'story.speaker.hero', next: 's15' },
    s15: { id: 's15', text: 'story.fourth.arrival.s15', speaker: 'story.speaker.reimu', next: 's16' },
    s16: { id: 's16', text: 'story.fourth.arrival.s16', narration: true, os: true, next: 's17' },
    s17: { id: 's17', text: 'story.fourth.arrival.s17', speaker: 'story.speaker.hero', next: 's18' },
    s18: { id: 's18', text: 'story.fourth.arrival.s18', speaker: 'story.speaker.reimu' },
  } },
  hungry: { id: 'touhou:fourth_hungry', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.hungry.s1', narration: true, os: true, next: 's2' },
    s2: { id: 's2', text: 'story.fourth.hungry.s2', speaker: 'story.speaker.rumia', next: 's3' },
    s3: { id: 's3', text: 'story.fourth.hungry.s3', speaker: 'story.speaker.rumia', next: 's4' },
    s4: { id: 's4', text: 'story.fourth.hungry.s4', speaker: 'story.speaker.hero', next: 's5' },
    s5: { id: 's5', text: 'story.fourth.hungry.s5', speaker: 'story.speaker.rumia', next: 's6' },
    s6: { id: 's6', text: 'story.fourth.hungry.s6', speaker: 'story.speaker.reimu', next: 's7' },
    s7: { id: 's7', text: 'story.fourth.hungry.s7', speaker: 'story.speaker.hero', next: 's8' },
    s8: { id: 's8', text: 'story.fourth.hungry.s8', speaker: 'story.speaker.reimu', next: 's9' },
    s9: { id: 's9', text: 'story.fourth.hungry.s9', narration: true, os: true, next: 's10', effects: [{ type: 'action', name: 'fourth.hugLeg' }] },
    s10: { id: 's10', text: 'story.fourth.hungry.s10', speaker: 'story.speaker.rumia', next: 's11' },
    s11: { id: 's11', text: 'story.fourth.hungry.s11', speaker: 'story.speaker.hero', next: 's12' },
    s12: { id: 's12', text: 'story.fourth.hungry.s12', speaker: 'story.speaker.rumia', next: 's13' },
    s13: { id: 's13', text: 'story.fourth.hungry.s13', speaker: 'story.speaker.hero', next: 's14' },
    s14: { id: 's14', text: 'story.fourth.hungry.s14', speaker: 'story.speaker.rumia' },
  } },
  account: { id: 'touhou:fourth_account', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.account.s1', speaker: 'story.speaker.hero', next: 's2' },
    s2: { id: 's2', text: 'story.fourth.account.s2', speaker: 'story.speaker.rumia', next: 's3' },
    s3: { id: 's3', text: 'story.fourth.account.s3', speaker: 'story.speaker.hero', next: 's4' },
    s4: { id: 's4', text: 'story.fourth.account.s4', speaker: 'story.speaker.rumia', next: 's5' },
    s5: { id: 's5', text: 'story.fourth.account.s5', speaker: 'story.speaker.hero', next: 's6' },
    s6: { id: 's6', text: 'story.fourth.account.s6', speaker: 'story.speaker.rumia', next: 's7' },
    s7: { id: 's7', text: 'story.fourth.account.s7', speaker: 'story.speaker.hero', next: 's8' },
    s8: { id: 's8', text: 'story.fourth.account.s8', speaker: 'story.speaker.rumia', next: 's9' },
    s9: { id: 's9', text: 'story.fourth.account.s9', speaker: 'story.speaker.hero', next: 's10' },
    s10: { id: 's10', text: 'story.fourth.account.s10', speaker: 'story.speaker.rumia', next: 's11' },
    s11: { id: 's11', text: 'story.fourth.account.s11', speaker: 'story.speaker.hero', next: 's12' },
    s12: { id: 's12', text: 'story.fourth.account.s12', speaker: 'story.speaker.rumia', next: 's13' },
    s13: { id: 's13', text: 'story.fourth.account.s13', speaker: 'story.speaker.hero', next: 's14' },
    s14: { id: 's14', text: 'story.fourth.account.s14', speaker: 'story.speaker.rumia', next: 's15' },
    s15: { id: 's15', text: 'story.fourth.account.s15', speaker: 'story.speaker.rumia', next: 's16' },
    s16: { id: 's16', text: 'story.fourth.account.s16', speaker: 'story.speaker.hero', next: 's17' },
    s17: { id: 's17', text: 'story.fourth.account.s17', speaker: 'story.speaker.rumia', next: 's18' },
    s18: { id: 's18', text: 'story.fourth.account.s18', speaker: 'story.speaker.hero', next: 's19' },
    s19: { id: 's19', text: 'story.fourth.account.s19', speaker: 'story.speaker.rumia', next: 's20' },
    s20: { id: 's20', text: 'story.fourth.account.s20', speaker: 'story.speaker.hero', next: 's21' },
    s21: { id: 's21', text: 'story.fourth.account.s21', narration: true, os: true, next: 's22' },
    s22: { id: 's22', text: 'story.fourth.account.s22', speaker: 'story.speaker.rumia', next: 's23' },
    s23: { id: 's23', text: 'story.fourth.account.s23', speaker: 'story.speaker.hero', next: 's24' },
    s24: { id: 's24', text: 'story.fourth.account.s24', speaker: 'story.speaker.rumia', next: 's25' },
    s25: { id: 's25', text: 'story.fourth.account.s25', speaker: 'story.speaker.hero', next: 's26' },
    s26: { id: 's26', text: 'story.fourth.account.s26', speaker: 'story.speaker.rumia', next: 's27' },
    s27: { id: 's27', text: 'story.fourth.account.s27', speaker: 'story.speaker.hero', next: 's28' },
    s28: { id: 's28', text: 'story.fourth.account.s28', speaker: 'story.speaker.rumia', next: 's29' },
    s29: { id: 's29', text: 'story.fourth.account.s29', speaker: 'story.speaker.hero', next: 's30' },
    s30: { id: 's30', text: 'story.fourth.account.s30', speaker: 'story.speaker.rumia', next: 's31' },
    s31: { id: 's31', text: 'story.fourth.account.s31', speaker: 'story.speaker.rumia', next: 's32' },
    s32: { id: 's32', text: 'story.fourth.account.s32', speaker: 'story.speaker.hero' },
  } },
  blocked: { id: 'touhou:fourth_blocked', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.blocked.s1', narration: true, os: true },
  } },
  idle: { id: 'touhou:fourth_idle', start: 's1', nodes: {
    s1: { id: 's1', text: 'story.fourth.idle.s1', speaker: 'story.speaker.rumia', next: 's2' },
    s2: { id: 's2', text: 'story.fourth.idle.s2', speaker: 'story.speaker.hero' },
  } },
}

// CG 只在咬手臂与打滚的动作旁白出现，不覆盖角色对白或抱小腿桥段。
bindStoryCG(FOURTH_TREES.rescue, ['s3'], storyCGs.rumiaBite)
bindStoryCG(FOURTH_TREES.hungry, ['s1'], storyCGs.rumiaRoll)

